(in-package :etap)

(defconstant +glyph-list+
  '((|fl| #\U+FB02) ; #### fl ligature not originally present
    (|fi| #\U+FB01) ; #### fi ligature not originally present
    (|A| #\U+0041) ;LATIN CAPITAL LETTER A
    (|AE| #\U+00C6) ;LATIN CAPITAL LETTER AE
    (|AEacute| #\U+01FC) ;LATIN CAPITAL LETTER AE WITH ACUTE
    (|Aacute| #\U+00C1) ;LATIN CAPITAL LETTER A WITH ACUTE
    (|Abreve| #\U+0102) ;LATIN CAPITAL LETTER A WITH BREVE
    (|Acircumflex| #\U+00C2) ;LATIN CAPITAL LETTER A WITH CIRCUMFLEX
    (|Adieresis| #\U+00C4) ;LATIN CAPITAL LETTER A WITH DIAERESIS
    (|Agrave| #\U+00C0) ;LATIN CAPITAL LETTER A WITH GRAVE
    (|Alpha| #\U+0391) ;GREEK CAPITAL LETTER ALPHA
    (|Alphatonos| #\U+0386) ;GREEK CAPITAL LETTER ALPHA WITH TONOS
    (|Amacron| #\U+0100) ;LATIN CAPITAL LETTER A WITH MACRON
    (|Aogonek| #\U+0104) ;LATIN CAPITAL LETTER A WITH OGONEK
    (|Aring| #\U+00C5) ;LATIN CAPITAL LETTER A WITH RING ABOVE
    (|Aringacute| #\U+01FA) ;LATIN CAPITAL LETTER A WITH RING ABOVE AND ACUTE
    (|Atilde| #\U+00C3) ;LATIN CAPITAL LETTER A WITH TILDE
    (|B| #\U+0042) ;LATIN CAPITAL LETTER B
    (|Beta| #\U+0392) ;GREEK CAPITAL LETTER BETA
    (|C| #\U+0043) ;LATIN CAPITAL LETTER C
    (|Cacute| #\U+0106) ;LATIN CAPITAL LETTER C WITH ACUTE
    (|Ccaron| #\U+010C) ;LATIN CAPITAL LETTER C WITH CARON
    (|Ccedilla| #\U+00C7) ;LATIN CAPITAL LETTER C WITH CEDILLA
    (|Ccircumflex| #\U+0108) ;LATIN CAPITAL LETTER C WITH CIRCUMFLEX
    (|Cdotaccent| #\U+010A) ;LATIN CAPITAL LETTER C WITH DOT ABOVE
    (|Chi| #\U+03A7) ;GREEK CAPITAL LETTER CHI
    (|D| #\U+0044) ;LATIN CAPITAL LETTER D
    (|Dcaron| #\U+010E) ;LATIN CAPITAL LETTER D WITH CARON
    (|Dcroat| #\U+0110) ;LATIN CAPITAL LETTER D WITH STROKE
    (|Delta| #\U+2206) ;INCREMENT
    (|E| #\U+0045) ;LATIN CAPITAL LETTER E
    (|Eacute| #\U+00C9) ;LATIN CAPITAL LETTER E WITH ACUTE
    (|Ebreve| #\U+0114) ;LATIN CAPITAL LETTER E WITH BREVE
    (|Ecaron| #\U+011A) ;LATIN CAPITAL LETTER E WITH CARON
    (|Ecircumflex| #\U+00CA) ;LATIN CAPITAL LETTER E WITH CIRCUMFLEX
    (|Edieresis| #\U+00CB) ;LATIN CAPITAL LETTER E WITH DIAERESIS
    (|Edotaccent| #\U+0116) ;LATIN CAPITAL LETTER E WITH DOT ABOVE
    (|Egrave| #\U+00C8) ;LATIN CAPITAL LETTER E WITH GRAVE
    (|Emacron| #\U+0112) ;LATIN CAPITAL LETTER E WITH MACRON
    (|Eng| #\U+014A) ;LATIN CAPITAL LETTER ENG
    (|Eogonek| #\U+0118) ;LATIN CAPITAL LETTER E WITH OGONEK
    (|Epsilon| #\U+0395) ;GREEK CAPITAL LETTER EPSILON
    (|Epsilontonos| #\U+0388) ;GREEK CAPITAL LETTER EPSILON WITH TONOS
    (|Eta| #\U+0397) ;GREEK CAPITAL LETTER ETA
    (|Etatonos| #\U+0389) ;GREEK CAPITAL LETTER ETA WITH TONOS
    (|Eth| #\U+00D0) ;LATIN CAPITAL LETTER ETH
    (|Euro| #\U+20AC) ;EURO SIGN
    (|F| #\U+0046) ;LATIN CAPITAL LETTER F
    (|G| #\U+0047) ;LATIN CAPITAL LETTER G
    (|Gamma| #\U+0393) ;GREEK CAPITAL LETTER GAMMA
    (|Gbreve| #\U+011E) ;LATIN CAPITAL LETTER G WITH BREVE
    (|Gcaron| #\U+01E6) ;LATIN CAPITAL LETTER G WITH CARON
    (|Gcircumflex| #\U+011C) ;LATIN CAPITAL LETTER G WITH CIRCUMFLEX
    (|Gdotaccent| #\U+0120) ;LATIN CAPITAL LETTER G WITH DOT ABOVE
    (|H| #\U+0048) ;LATIN CAPITAL LETTER H
    (|H18533| #\U+25CF) ;BLACK CIRCLE
    (|H18543| #\U+25AA) ;BLACK SMALL SQUARE
    (|H18551| #\U+25AB) ;WHITE SMALL SQUARE
    (|H22073| #\U+25A1) ;WHITE SQUARE
    (|Hbar| #\U+0126) ;LATIN CAPITAL LETTER H WITH STROKE
    (|Hcircumflex| #\U+0124) ;LATIN CAPITAL LETTER H WITH CIRCUMFLEX
    (|I| #\U+0049) ;LATIN CAPITAL LETTER I
    (|IJ| #\U+0132) ;LATIN CAPITAL LIGATURE IJ
    (|Iacute| #\U+00CD) ;LATIN CAPITAL LETTER I WITH ACUTE
    (|Ibreve| #\U+012C) ;LATIN CAPITAL LETTER I WITH BREVE
    (|Icircumflex| #\U+00CE) ;LATIN CAPITAL LETTER I WITH CIRCUMFLEX
    (|Idieresis| #\U+00CF) ;LATIN CAPITAL LETTER I WITH DIAERESIS
    (|Idotaccent| #\U+0130) ;LATIN CAPITAL LETTER I WITH DOT ABOVE
    (|Ifraktur| #\U+2111) ;BLACK-LETTER CAPITAL I
    (|Igrave| #\U+00CC) ;LATIN CAPITAL LETTER I WITH GRAVE
    (|Imacron| #\U+012A) ;LATIN CAPITAL LETTER I WITH MACRON
    (|Iogonek| #\U+012E) ;LATIN CAPITAL LETTER I WITH OGONEK
    (|Iota| #\U+0399) ;GREEK CAPITAL LETTER IOTA
    (|Iotadieresis| #\U+03AA) ;GREEK CAPITAL LETTER IOTA WITH DIALYTIKA
    (|Iotatonos| #\U+038A) ;GREEK CAPITAL LETTER IOTA WITH TONOS
    (|Itilde| #\U+0128) ;LATIN CAPITAL LETTER I WITH TILDE
    (|J| #\U+004A) ;LATIN CAPITAL LETTER J
    (|Jcircumflex| #\U+0134) ;LATIN CAPITAL LETTER J WITH CIRCUMFLEX
    (|K| #\U+004B) ;LATIN CAPITAL LETTER K
    (|Kappa| #\U+039A) ;GREEK CAPITAL LETTER KAPPA
    (|L| #\U+004C) ;LATIN CAPITAL LETTER L
    (|Lacute| #\U+0139) ;LATIN CAPITAL LETTER L WITH ACUTE
    (|Lambda| #\U+039B) ;GREEK CAPITAL LETTER LAMDA
    (|Lcaron| #\U+013D) ;LATIN CAPITAL LETTER L WITH CARON
    (|Ldot| #\U+013F) ;LATIN CAPITAL LETTER L WITH MIDDLE DOT
    (|Lslash| #\U+0141) ;LATIN CAPITAL LETTER L WITH STROKE
    (|M| #\U+004D) ;LATIN CAPITAL LETTER M
    (|Mu| #\U+039C) ;GREEK CAPITAL LETTER MU
    (|N| #\U+004E) ;LATIN CAPITAL LETTER N
    (|Nacute| #\U+0143) ;LATIN CAPITAL LETTER N WITH ACUTE
    (|Ncaron| #\U+0147) ;LATIN CAPITAL LETTER N WITH CARON
    (|Ntilde| #\U+00D1) ;LATIN CAPITAL LETTER N WITH TILDE
    (|Nu| #\U+039D) ;GREEK CAPITAL LETTER NU
    (|O| #\U+004F) ;LATIN CAPITAL LETTER O
    (|OE| #\U+0152) ;LATIN CAPITAL LIGATURE OE
    (|Oacute| #\U+00D3) ;LATIN CAPITAL LETTER O WITH ACUTE
    (|Obreve| #\U+014E) ;LATIN CAPITAL LETTER O WITH BREVE
    (|Ocircumflex| #\U+00D4) ;LATIN CAPITAL LETTER O WITH CIRCUMFLEX
    (|Odieresis| #\U+00D6) ;LATIN CAPITAL LETTER O WITH DIAERESIS
    (|Ograve| #\U+00D2) ;LATIN CAPITAL LETTER O WITH GRAVE
    (|Ohorn| #\U+01A0) ;LATIN CAPITAL LETTER O WITH HORN
    (|Ohungarumlaut| #\U+0150) ;LATIN CAPITAL LETTER O WITH DOUBLE ACUTE
    (|Omacron| #\U+014C) ;LATIN CAPITAL LETTER O WITH MACRON
    (|Omega| #\U+2126) ;OHM SIGN
    (|Omegatonos| #\U+038F) ;GREEK CAPITAL LETTER OMEGA WITH TONOS
    (|Omicron| #\U+039F) ;GREEK CAPITAL LETTER OMICRON
    (|Omicrontonos| #\U+038C) ;GREEK CAPITAL LETTER OMICRON WITH TONOS
    (|Oslash| #\U+00D8) ;LATIN CAPITAL LETTER O WITH STROKE
    (|Oslashacute| #\U+01FE) ;LATIN CAPITAL LETTER O WITH STROKE AND ACUTE
    (|Otilde| #\U+00D5) ;LATIN CAPITAL LETTER O WITH TILDE
    (|P| #\U+0050) ;LATIN CAPITAL LETTER P
    (|Phi| #\U+03A6) ;GREEK CAPITAL LETTER PHI
    (|Pi| #\U+03A0) ;GREEK CAPITAL LETTER PI
    (|Psi| #\U+03A8) ;GREEK CAPITAL LETTER PSI
    (|Q| #\U+0051) ;LATIN CAPITAL LETTER Q
    (|R| #\U+0052) ;LATIN CAPITAL LETTER R
    (|Racute| #\U+0154) ;LATIN CAPITAL LETTER R WITH ACUTE
    (|Rcaron| #\U+0158) ;LATIN CAPITAL LETTER R WITH CARON
    (|Rfraktur| #\U+211C) ;BLACK-LETTER CAPITAL R
    (|Rho| #\U+03A1) ;GREEK CAPITAL LETTER RHO
    (|S| #\U+0053) ;LATIN CAPITAL LETTER S
    (|SF010000| #\U+250C) ;BOX DRAWINGS LIGHT DOWN AND RIGHT
    (|SF020000| #\U+2514) ;BOX DRAWINGS LIGHT UP AND RIGHT
    (|SF030000| #\U+2510) ;BOX DRAWINGS LIGHT DOWN AND LEFT
    (|SF040000| #\U+2518) ;BOX DRAWINGS LIGHT UP AND LEFT
    (|SF050000| #\U+253C) ;BOX DRAWINGS LIGHT VERTICAL AND HORIZONTAL
    (|SF060000| #\U+252C) ;BOX DRAWINGS LIGHT DOWN AND HORIZONTAL
    (|SF070000| #\U+2534) ;BOX DRAWINGS LIGHT UP AND HORIZONTAL
    (|SF080000| #\U+251C) ;BOX DRAWINGS LIGHT VERTICAL AND RIGHT
    (|SF090000| #\U+2524) ;BOX DRAWINGS LIGHT VERTICAL AND LEFT
    (|SF100000| #\U+2500) ;BOX DRAWINGS LIGHT HORIZONTAL
    (|SF110000| #\U+2502) ;BOX DRAWINGS LIGHT VERTICAL
    (|SF190000| #\U+2561) ;BOX DRAWINGS VERTICAL SINGLE AND LEFT DOUBLE
    (|SF200000| #\U+2562) ;BOX DRAWINGS VERTICAL DOUBLE AND LEFT SINGLE
    (|SF210000| #\U+2556) ;BOX DRAWINGS DOWN DOUBLE AND LEFT SINGLE
    (|SF220000| #\U+2555) ;BOX DRAWINGS DOWN SINGLE AND LEFT DOUBLE
    (|SF230000| #\U+2563) ;BOX DRAWINGS DOUBLE VERTICAL AND LEFT
    (|SF240000| #\U+2551) ;BOX DRAWINGS DOUBLE VERTICAL
    (|SF250000| #\U+2557) ;BOX DRAWINGS DOUBLE DOWN AND LEFT
    (|SF260000| #\U+255D) ;BOX DRAWINGS DOUBLE UP AND LEFT
    (|SF270000| #\U+255C) ;BOX DRAWINGS UP DOUBLE AND LEFT SINGLE
    (|SF280000| #\U+255B) ;BOX DRAWINGS UP SINGLE AND LEFT DOUBLE
    (|SF360000| #\U+255E) ;BOX DRAWINGS VERTICAL SINGLE AND RIGHT DOUBLE
    (|SF370000| #\U+255F) ;BOX DRAWINGS VERTICAL DOUBLE AND RIGHT SINGLE
    (|SF380000| #\U+255A) ;BOX DRAWINGS DOUBLE UP AND RIGHT
    (|SF390000| #\U+2554) ;BOX DRAWINGS DOUBLE DOWN AND RIGHT
    (|SF400000| #\U+2569) ;BOX DRAWINGS DOUBLE UP AND HORIZONTAL
    (|SF410000| #\U+2566) ;BOX DRAWINGS DOUBLE DOWN AND HORIZONTAL
    (|SF420000| #\U+2560) ;BOX DRAWINGS DOUBLE VERTICAL AND RIGHT
    (|SF430000| #\U+2550) ;BOX DRAWINGS DOUBLE HORIZONTAL
    (|SF440000| #\U+256C) ;BOX DRAWINGS DOUBLE VERTICAL AND HORIZONTAL
    (|SF450000| #\U+2567) ;BOX DRAWINGS UP SINGLE AND HORIZONTAL DOUBLE
    (|SF460000| #\U+2568) ;BOX DRAWINGS UP DOUBLE AND HORIZONTAL SINGLE
    (|SF470000| #\U+2564) ;BOX DRAWINGS DOWN SINGLE AND HORIZONTAL DOUBLE
    (|SF480000| #\U+2565) ;BOX DRAWINGS DOWN DOUBLE AND HORIZONTAL SINGLE
    (|SF490000| #\U+2559) ;BOX DRAWINGS UP DOUBLE AND RIGHT SINGLE
    (|SF500000| #\U+2558) ;BOX DRAWINGS UP SINGLE AND RIGHT DOUBLE
    (|SF510000| #\U+2552) ;BOX DRAWINGS DOWN SINGLE AND RIGHT DOUBLE
    (|SF520000| #\U+2553) ;BOX DRAWINGS DOWN DOUBLE AND RIGHT SINGLE
    (|SF530000| #\U+256B) ;BOX DRAWINGS VERTICAL DOUBLE AND HORIZONTAL SINGLE
    (|SF540000| #\U+256A) ;BOX DRAWINGS VERTICAL SINGLE AND HORIZONTAL DOUBLE
    (|Sacute| #\U+015A) ;LATIN CAPITAL LETTER S WITH ACUTE
    (|Scaron| #\U+0160) ;LATIN CAPITAL LETTER S WITH CARON
    (|Scedilla| #\U+015E) ;LATIN CAPITAL LETTER S WITH CEDILLA
    (|Scircumflex| #\U+015C) ;LATIN CAPITAL LETTER S WITH CIRCUMFLEX
    (|Sigma| #\U+03A3) ;GREEK CAPITAL LETTER SIGMA
    (|T| #\U+0054) ;LATIN CAPITAL LETTER T
    (|Tau| #\U+03A4) ;GREEK CAPITAL LETTER TAU
    (|Tbar| #\U+0166) ;LATIN CAPITAL LETTER T WITH STROKE
    (|Tcaron| #\U+0164) ;LATIN CAPITAL LETTER T WITH CARON
    (|Theta| #\U+0398) ;GREEK CAPITAL LETTER THETA
    (|Thorn| #\U+00DE) ;LATIN CAPITAL LETTER THORN
    (|U| #\U+0055) ;LATIN CAPITAL LETTER U
    (|Uacute| #\U+00DA) ;LATIN CAPITAL LETTER U WITH ACUTE
    (|Ubreve| #\U+016C) ;LATIN CAPITAL LETTER U WITH BREVE
    (|Ucircumflex| #\U+00DB) ;LATIN CAPITAL LETTER U WITH CIRCUMFLEX
    (|Udieresis| #\U+00DC) ;LATIN CAPITAL LETTER U WITH DIAERESIS
    (|Ugrave| #\U+00D9) ;LATIN CAPITAL LETTER U WITH GRAVE
    (|Uhorn| #\U+01AF) ;LATIN CAPITAL LETTER U WITH HORN
    (|Uhungarumlaut| #\U+0170) ;LATIN CAPITAL LETTER U WITH DOUBLE ACUTE
    (|Umacron| #\U+016A) ;LATIN CAPITAL LETTER U WITH MACRON
    (|Uogonek| #\U+0172) ;LATIN CAPITAL LETTER U WITH OGONEK
    (|Upsilon| #\U+03A5) ;GREEK CAPITAL LETTER UPSILON
    (|Upsilon1| #\U+03D2) ;GREEK UPSILON WITH HOOK SYMBOL
    (|Upsilondieresis| #\U+03AB) ;GREEK CAPITAL LETTER UPSILON WITH DIALYTIKA
    (|Upsilontonos| #\U+038E) ;GREEK CAPITAL LETTER UPSILON WITH TONOS
    (|Uring| #\U+016E) ;LATIN CAPITAL LETTER U WITH RING ABOVE
    (|Utilde| #\U+0168) ;LATIN CAPITAL LETTER U WITH TILDE
    (|V| #\U+0056) ;LATIN CAPITAL LETTER V
    (|W| #\U+0057) ;LATIN CAPITAL LETTER W
    (|Wacute| #\U+1E82) ;LATIN CAPITAL LETTER W WITH ACUTE
    (|Wcircumflex| #\U+0174) ;LATIN CAPITAL LETTER W WITH CIRCUMFLEX
    (|Wdieresis| #\U+1E84) ;LATIN CAPITAL LETTER W WITH DIAERESIS
    (|Wgrave| #\U+1E80) ;LATIN CAPITAL LETTER W WITH GRAVE
    (|X| #\U+0058) ;LATIN CAPITAL LETTER X
    (|Xi| #\U+039E) ;GREEK CAPITAL LETTER XI
    (|Y| #\U+0059) ;LATIN CAPITAL LETTER Y
    (|Yacute| #\U+00DD) ;LATIN CAPITAL LETTER Y WITH ACUTE
    (|Ycircumflex| #\U+0176) ;LATIN CAPITAL LETTER Y WITH CIRCUMFLEX
    (|Ydieresis| #\U+0178) ;LATIN CAPITAL LETTER Y WITH DIAERESIS
    (|Ygrave| #\U+1EF2) ;LATIN CAPITAL LETTER Y WITH GRAVE
    (|Z| #\U+005A) ;LATIN CAPITAL LETTER Z
    (|Zacute| #\U+0179) ;LATIN CAPITAL LETTER Z WITH ACUTE
    (|Zcaron| #\U+017D) ;LATIN CAPITAL LETTER Z WITH CARON
    (|Zdotaccent| #\U+017B) ;LATIN CAPITAL LETTER Z WITH DOT ABOVE
    (|Zeta| #\U+0396) ;GREEK CAPITAL LETTER ZETA
    (|a| #\U+0061) ;LATIN SMALL LETTER A
    (|aacute| #\U+00E1) ;LATIN SMALL LETTER A WITH ACUTE
    (|abreve| #\U+0103) ;LATIN SMALL LETTER A WITH BREVE
    (|acircumflex| #\U+00E2) ;LATIN SMALL LETTER A WITH CIRCUMFLEX
    (|acute| #\U+00B4) ;ACUTE ACCENT
    (|acutecomb| #\U+0301) ;COMBINING ACUTE ACCENT
    (|adieresis| #\U+00E4) ;LATIN SMALL LETTER A WITH DIAERESIS
    (|ae| #\U+00E6) ;LATIN SMALL LETTER AE
    (|aeacute| #\U+01FD) ;LATIN SMALL LETTER AE WITH ACUTE
    (|agrave| #\U+00E0) ;LATIN SMALL LETTER A WITH GRAVE
    (|aleph| #\U+2135) ;ALEF SYMBOL
    (|alpha| #\U+03B1) ;GREEK SMALL LETTER ALPHA
    (|alphatonos| #\U+03AC) ;GREEK SMALL LETTER ALPHA WITH TONOS
    (|amacron| #\U+0101) ;LATIN SMALL LETTER A WITH MACRON
    (|ampersand| #\U+0026) ;AMPERSAND
    (|angle| #\U+2220) ;ANGLE
    (|angleleft| #\U+2329) ;LEFT-POINTING ANGLE BRACKET
    (|angleright| #\U+232A) ;RIGHT-POINTING ANGLE BRACKET
    (|anoteleia| #\U+0387) ;GREEK ANO TELEIA
    (|aogonek| #\U+0105) ;LATIN SMALL LETTER A WITH OGONEK
    (|approxequal| #\U+2248) ;ALMOST EQUAL TO
    (|aring| #\U+00E5) ;LATIN SMALL LETTER A WITH RING ABOVE
    (|aringacute| #\U+01FB) ;LATIN SMALL LETTER A WITH RING ABOVE AND ACUTE
    (|arrowboth| #\U+2194) ;LEFT RIGHT ARROW
    (|arrowdblboth| #\U+21D4) ;LEFT RIGHT DOUBLE ARROW
    (|arrowdbldown| #\U+21D3) ;DOWNWARDS DOUBLE ARROW
    (|arrowdblleft| #\U+21D0) ;LEFTWARDS DOUBLE ARROW
    (|arrowdblright| #\U+21D2) ;RIGHTWARDS DOUBLE ARROW
    (|arrowdblup| #\U+21D1) ;UPWARDS DOUBLE ARROW
    (|arrowdown| #\U+2193) ;DOWNWARDS ARROW
    (|arrowleft| #\U+2190) ;LEFTWARDS ARROW
    (|arrowright| #\U+2192) ;RIGHTWARDS ARROW
    (|arrowup| #\U+2191) ;UPWARDS ARROW
    (|arrowupdn| #\U+2195) ;UP DOWN ARROW
    (|arrowupdnbse| #\U+21A8) ;UP DOWN ARROW WITH BASE
    (|asciicircum| #\U+005E) ;CIRCUMFLEX ACCENT
    (|asciitilde| #\U+007E) ;TILDE
    (|asterisk| #\U+002A) ;ASTERISK
    (|asteriskmath| #\U+2217) ;ASTERISK OPERATOR
    (|at| #\U+0040) ;COMMERCIAL AT
    (|atilde| #\U+00E3) ;LATIN SMALL LETTER A WITH TILDE
    (|b| #\U+0062) ;LATIN SMALL LETTER B
    (|backslash| #\U+005C) ;REVERSE SOLIDUS
    (|bar| #\U+007C) ;VERTICAL LINE
    (|beta| #\U+03B2) ;GREEK SMALL LETTER BETA
    (|block| #\U+2588) ;FULL BLOCK
    (|braceleft| #\U+007B) ;LEFT CURLY BRACKET
    (|braceright| #\U+007D) ;RIGHT CURLY BRACKET
    (|bracketleft| #\U+005B) ;LEFT SQUARE BRACKET
    (|bracketright| #\U+005D) ;RIGHT SQUARE BRACKET
    (|breve| #\U+02D8) ;BREVE
    (|brokenbar| #\U+00A6) ;BROKEN BAR
    (|bullet| #\U+2022) ;BULLET
    (|c| #\U+0063) ;LATIN SMALL LETTER C
    (|cacute| #\U+0107) ;LATIN SMALL LETTER C WITH ACUTE
    (|caron| #\U+02C7) ;CARON
    (|carriagereturn| #\U+21B5) ;DOWNWARDS ARROW WITH CORNER LEFTWARDS
    (|ccaron| #\U+010D) ;LATIN SMALL LETTER C WITH CARON
    (|ccedilla| #\U+00E7) ;LATIN SMALL LETTER C WITH CEDILLA
    (|ccircumflex| #\U+0109) ;LATIN SMALL LETTER C WITH CIRCUMFLEX
    (|cdotaccent| #\U+010B) ;LATIN SMALL LETTER C WITH DOT ABOVE
    (|cedilla| #\U+00B8) ;CEDILLA
    (|cent| #\U+00A2) ;CENT SIGN
    (|chi| #\U+03C7) ;GREEK SMALL LETTER CHI
    (|circle| #\U+25CB) ;WHITE CIRCLE
    (|circlemultiply| #\U+2297) ;CIRCLED TIMES
    (|circleplus| #\U+2295) ;CIRCLED PLUS
    (|circumflex| #\U+02C6) ;MODIFIER LETTER CIRCUMFLEX ACCENT
    (|club| #\U+2663) ;BLACK CLUB SUIT
    (|colon| #\U+003A) ;COLON
    (|colonmonetary| #\U+20A1) ;COLON SIGN
    (|comma| #\U+002C) ;COMMA
    (|congruent| #\U+2245) ;APPROXIMATELY EQUAL TO
    (|copyright| #\U+00A9) ;COPYRIGHT SIGN
    (|currency| #\U+00A4) ;CURRENCY SIGN
    (|d| #\U+0064) ;LATIN SMALL LETTER D
    (|dagger| #\U+2020) ;DAGGER
    (|daggerdbl| #\U+2021) ;DOUBLE DAGGER
    (|dcaron| #\U+010F) ;LATIN SMALL LETTER D WITH CARON
    (|dcroat| #\U+0111) ;LATIN SMALL LETTER D WITH STROKE
    (|degree| #\U+00B0) ;DEGREE SIGN
    (|delta| #\U+03B4) ;GREEK SMALL LETTER DELTA
    (|diamond| #\U+2666) ;BLACK DIAMOND SUIT
    (|dieresis| #\U+00A8) ;DIAERESIS
    (|dieresistonos| #\U+0385) ;GREEK DIALYTIKA TONOS
    (|divide| #\U+00F7) ;DIVISION SIGN
    (|dkshade| #\U+2593) ;DARK SHADE
    (|dnblock| #\U+2584) ;LOWER HALF BLOCK
    (|dollar| #\U+0024) ;DOLLAR SIGN
    (|dong| #\U+20AB) ;DONG SIGN
    (|dotaccent| #\U+02D9) ;DOT ABOVE
    (|dotbelowcomb| #\U+0323) ;COMBINING DOT BELOW
    (|dotlessi| #\U+0131) ;LATIN SMALL LETTER DOTLESS I
    (|dotmath| #\U+22C5) ;DOT OPERATOR
    (|e| #\U+0065) ;LATIN SMALL LETTER E
    (|eacute| #\U+00E9) ;LATIN SMALL LETTER E WITH ACUTE
    (|ebreve| #\U+0115) ;LATIN SMALL LETTER E WITH BREVE
    (|ecaron| #\U+011B) ;LATIN SMALL LETTER E WITH CARON
    (|ecircumflex| #\U+00EA) ;LATIN SMALL LETTER E WITH CIRCUMFLEX
    (|edieresis| #\U+00EB) ;LATIN SMALL LETTER E WITH DIAERESIS
    (|edotaccent| #\U+0117) ;LATIN SMALL LETTER E WITH DOT ABOVE
    (|egrave| #\U+00E8) ;LATIN SMALL LETTER E WITH GRAVE
    (|eight| #\U+0038) ;DIGIT EIGHT
    (|element| #\U+2208) ;ELEMENT OF
    (|ellipsis| #\U+2026) ;HORIZONTAL ELLIPSIS
    (|emacron| #\U+0113) ;LATIN SMALL LETTER E WITH MACRON
    (|emdash| #\U+2014) ;EM DASH
    (|emptyset| #\U+2205) ;EMPTY SET
    (|endash| #\U+2013) ;EN DASH
    (|eng| #\U+014B) ;LATIN SMALL LETTER ENG
    (|eogonek| #\U+0119) ;LATIN SMALL LETTER E WITH OGONEK
    (|epsilon| #\U+03B5) ;GREEK SMALL LETTER EPSILON
    (|epsilontonos| #\U+03AD) ;GREEK SMALL LETTER EPSILON WITH TONOS
    (|equal| #\U+003D) ;EQUALS SIGN
    (|equivalence| #\U+2261) ;IDENTICAL TO
    (|estimated| #\U+212E) ;ESTIMATED SYMBOL
    (|eta| #\U+03B7) ;GREEK SMALL LETTER ETA
    (|etatonos| #\U+03AE) ;GREEK SMALL LETTER ETA WITH TONOS
    (|eth| #\U+00F0) ;LATIN SMALL LETTER ETH
    (|exclam| #\U+0021) ;EXCLAMATION MARK
    (|exclamdbl| #\U+203C) ;DOUBLE EXCLAMATION MARK
    (|exclamdown| #\U+00A1) ;INVERTED EXCLAMATION MARK
    (|existential| #\U+2203) ;THERE EXISTS
    (|f| #\U+0066) ;LATIN SMALL LETTER F
    (|female| #\U+2640) ;FEMALE SIGN
    (|figuredash| #\U+2012) ;FIGURE DASH
    (|filledbox| #\U+25A0) ;BLACK SQUARE
    (|filledrect| #\U+25AC) ;BLACK RECTANGLE
    (|five| #\U+0035) ;DIGIT FIVE
    (|fiveeighths| #\U+215D) ;VULGAR FRACTION FIVE EIGHTHS
    (|florin| #\U+0192) ;LATIN SMALL LETTER F WITH HOOK
    (|four| #\U+0034) ;DIGIT FOUR
    (|fraction| #\U+2044) ;FRACTION SLASH
    (|franc| #\U+20A3) ;FRENCH FRANC SIGN
    (|g| #\U+0067) ;LATIN SMALL LETTER G
    (|gamma| #\U+03B3) ;GREEK SMALL LETTER GAMMA
    (|gbreve| #\U+011F) ;LATIN SMALL LETTER G WITH BREVE
    (|gcaron| #\U+01E7) ;LATIN SMALL LETTER G WITH CARON
    (|gcircumflex| #\U+011D) ;LATIN SMALL LETTER G WITH CIRCUMFLEX
    (|gdotaccent| #\U+0121) ;LATIN SMALL LETTER G WITH DOT ABOVE
    (|germandbls| #\U+00DF) ;LATIN SMALL LETTER SHARP S
    (|gradient| #\U+2207) ;NABLA
    (|grave| #\U+0060) ;GRAVE ACCENT
    (|gravecomb| #\U+0300) ;COMBINING GRAVE ACCENT
    (|greater| #\U+003E) ;GREATER-THAN SIGN
    (|greaterequal| #\U+2265) ;GREATER-THAN OR EQUAL TO
    (|guillemotleft| #\U+00AB) ;LEFT-POINTING DOUBLE ANGLE QUOTATION MARK
    (|guillemotright| #\U+00BB) ;RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK
    (|guilsinglleft| #\U+2039) ;SINGLE LEFT-POINTING ANGLE QUOTATION MARK
    (|guilsinglright| #\U+203A) ;SINGLE RIGHT-POINTING ANGLE QUOTATION MARK
    (|h| #\U+0068) ;LATIN SMALL LETTER H
    (|hbar| #\U+0127) ;LATIN SMALL LETTER H WITH STROKE
    (|hcircumflex| #\U+0125) ;LATIN SMALL LETTER H WITH CIRCUMFLEX
    (|heart| #\U+2665) ;BLACK HEART SUIT
    (|hookabovecomb| #\U+0309) ;COMBINING HOOK ABOVE
    (|house| #\U+2302) ;HOUSE
    (|hungarumlaut| #\U+02DD) ;DOUBLE ACUTE ACCENT
    (|hyphen| #\U+002D) ;HYPHEN-MINUS
    (|i| #\U+0069) ;LATIN SMALL LETTER I
    (|iacute| #\U+00ED) ;LATIN SMALL LETTER I WITH ACUTE
    (|ibreve| #\U+012D) ;LATIN SMALL LETTER I WITH BREVE
    (|icircumflex| #\U+00EE) ;LATIN SMALL LETTER I WITH CIRCUMFLEX
    (|idieresis| #\U+00EF) ;LATIN SMALL LETTER I WITH DIAERESIS
    (|igrave| #\U+00EC) ;LATIN SMALL LETTER I WITH GRAVE
    (|ij| #\U+0133) ;LATIN SMALL LIGATURE IJ
    (|imacron| #\U+012B) ;LATIN SMALL LETTER I WITH MACRON
    (|infinity| #\U+221E) ;INFINITY
    (|integral| #\U+222B) ;INTEGRAL
    (|integralbt| #\U+2321) ;BOTTOM HALF INTEGRAL
    (|integraltp| #\U+2320) ;TOP HALF INTEGRAL
    (|intersection| #\U+2229) ;INTERSECTION
    (|invbullet| #\U+25D8) ;INVERSE BULLET
    (|invcircle| #\U+25D9) ;INVERSE WHITE CIRCLE
    (|invsmileface| #\U+263B) ;BLACK SMILING FACE
    (|iogonek| #\U+012F) ;LATIN SMALL LETTER I WITH OGONEK
    (|iota| #\U+03B9) ;GREEK SMALL LETTER IOTA
    (|iotadieresis| #\U+03CA) ;GREEK SMALL LETTER IOTA WITH DIALYTIKA
    (|iotadieresistonos| #\U+0390) ;GREEK SMALL LETTER IOTA WITH DIALYTIKA AND TONOS
    (|iotatonos| #\U+03AF) ;GREEK SMALL LETTER IOTA WITH TONOS
    (|itilde| #\U+0129) ;LATIN SMALL LETTER I WITH TILDE
    (|j| #\U+006A) ;LATIN SMALL LETTER J
    (|jcircumflex| #\U+0135) ;LATIN SMALL LETTER J WITH CIRCUMFLEX
    (|k| #\U+006B) ;LATIN SMALL LETTER K
    (|kappa| #\U+03BA) ;GREEK SMALL LETTER KAPPA
    (|kgreenlandic| #\U+0138) ;LATIN SMALL LETTER KRA
    (|l| #\U+006C) ;LATIN SMALL LETTER L
    (|lacute| #\U+013A) ;LATIN SMALL LETTER L WITH ACUTE
    (|lambda| #\U+03BB) ;GREEK SMALL LETTER LAMDA
    (|lcaron| #\U+013E) ;LATIN SMALL LETTER L WITH CARON
    (|ldot| #\U+0140) ;LATIN SMALL LETTER L WITH MIDDLE DOT
    (|less| #\U+003C) ;LESS-THAN SIGN
    (|lessequal| #\U+2264) ;LESS-THAN OR EQUAL TO
    (|lfblock| #\U+258C) ;LEFT HALF BLOCK
    (|lira| #\U+20A4) ;LIRA SIGN
    (|logicaland| #\U+2227) ;LOGICAL AND
    (|logicalnot| #\U+00AC) ;NOT SIGN
    (|logicalor| #\U+2228) ;LOGICAL OR
    (|longs| #\U+017F) ;LATIN SMALL LETTER LONG S
    (|lozenge| #\U+25CA) ;LOZENGE
    (|lslash| #\U+0142) ;LATIN SMALL LETTER L WITH STROKE
    (|ltshade| #\U+2591) ;LIGHT SHADE
    (|m| #\U+006D) ;LATIN SMALL LETTER M
    (|macron| #\U+00AF) ;MACRON
    (|male| #\U+2642) ;MALE SIGN
    (|minus| #\U+2212) ;MINUS SIGN
    (|minute| #\U+2032) ;PRIME
    (|mu| #\U+00B5) ;MICRO SIGN
    (|multiply| #\U+00D7) ;MULTIPLICATION SIGN
    (|musicalnote| #\U+266A) ;EIGHTH NOTE
    (|musicalnotedbl| #\U+266B) ;BEAMED EIGHTH NOTES
    (|n| #\U+006E) ;LATIN SMALL LETTER N
    (|nacute| #\U+0144) ;LATIN SMALL LETTER N WITH ACUTE
    (|napostrophe| #\U+0149) ;LATIN SMALL LETTER N PRECEDED BY APOSTROPHE
    (|ncaron| #\U+0148) ;LATIN SMALL LETTER N WITH CARON
    (|nine| #\U+0039) ;DIGIT NINE
    (|notelement| #\U+2209) ;NOT AN ELEMENT OF
    (|notequal| #\U+2260) ;NOT EQUAL TO
    (|notsubset| #\U+2284) ;NOT A SUBSET OF
    (|ntilde| #\U+00F1) ;LATIN SMALL LETTER N WITH TILDE
    (|nu| #\U+03BD) ;GREEK SMALL LETTER NU
    (|numbersign| #\U+0023) ;NUMBER SIGN
    (|o| #\U+006F) ;LATIN SMALL LETTER O
    (|oacute| #\U+00F3) ;LATIN SMALL LETTER O WITH ACUTE
    (|obreve| #\U+014F) ;LATIN SMALL LETTER O WITH BREVE
    (|ocircumflex| #\U+00F4) ;LATIN SMALL LETTER O WITH CIRCUMFLEX
    (|odieresis| #\U+00F6) ;LATIN SMALL LETTER O WITH DIAERESIS
    (|oe| #\U+0153) ;LATIN SMALL LIGATURE OE
    (|ogonek| #\U+02DB) ;OGONEK
    (|ograve| #\U+00F2) ;LATIN SMALL LETTER O WITH GRAVE
    (|ohorn| #\U+01A1) ;LATIN SMALL LETTER O WITH HORN
    (|ohungarumlaut| #\U+0151) ;LATIN SMALL LETTER O WITH DOUBLE ACUTE
    (|omacron| #\U+014D) ;LATIN SMALL LETTER O WITH MACRON
    (|omega| #\U+03C9) ;GREEK SMALL LETTER OMEGA
    (|omega1| #\U+03D6) ;GREEK PI SYMBOL
    (|omegatonos| #\U+03CE) ;GREEK SMALL LETTER OMEGA WITH TONOS
    (|omicron| #\U+03BF) ;GREEK SMALL LETTER OMICRON
    (|omicrontonos| #\U+03CC) ;GREEK SMALL LETTER OMICRON WITH TONOS
    (|one| #\U+0031) ;DIGIT ONE
    (|onedotenleader| #\U+2024) ;ONE DOT LEADER
    (|oneeighth| #\U+215B) ;VULGAR FRACTION ONE EIGHTH
    (|onehalf| #\U+00BD) ;VULGAR FRACTION ONE HALF
    (|onequarter| #\U+00BC) ;VULGAR FRACTION ONE QUARTER
    (|onethird| #\U+2153) ;VULGAR FRACTION ONE THIRD
    (|openbullet| #\U+25E6) ;WHITE BULLET
    (|ordfeminine| #\U+00AA) ;FEMININE ORDINAL INDICATOR
    (|ordmasculine| #\U+00BA) ;MASCULINE ORDINAL INDICATOR
    (|orthogonal| #\U+221F) ;RIGHT ANGLE
    (|oslash| #\U+00F8) ;LATIN SMALL LETTER O WITH STROKE
    (|oslashacute| #\U+01FF) ;LATIN SMALL LETTER O WITH STROKE AND ACUTE
    (|otilde| #\U+00F5) ;LATIN SMALL LETTER O WITH TILDE
    (|p| #\U+0070) ;LATIN SMALL LETTER P
    (|paragraph| #\U+00B6) ;PILCROW SIGN
    (|parenleft| #\U+0028) ;LEFT PARENTHESIS
    (|parenright| #\U+0029) ;RIGHT PARENTHESIS
    (|partialdiff| #\U+2202) ;PARTIAL DIFFERENTIAL
    (|percent| #\U+0025) ;PERCENT SIGN
    (|period| #\U+002E) ;FULL STOP
    (|periodcentered| #\U+00B7) ;MIDDLE DOT
    (|perpendicular| #\U+22A5) ;UP TACK
    (|perthousand| #\U+2030) ;PER MILLE SIGN
    (|peseta| #\U+20A7) ;PESETA SIGN
    (|phi| #\U+03C6) ;GREEK SMALL LETTER PHI
    (|phi1| #\U+03D5) ;GREEK PHI SYMBOL
    (|pi| #\U+03C0) ;GREEK SMALL LETTER PI
    (|plus| #\U+002B) ;PLUS SIGN
    (|plusminus| #\U+00B1) ;PLUS-MINUS SIGN
    (|prescription| #\U+211E) ;PRESCRIPTION TAKE
    (|product| #\U+220F) ;N-ARY PRODUCT
    (|propersubset| #\U+2282) ;SUBSET OF
    (|propersuperset| #\U+2283) ;SUPERSET OF
    (|proportional| #\U+221D) ;PROPORTIONAL TO
    (|psi| #\U+03C8) ;GREEK SMALL LETTER PSI
    (|q| #\U+0071) ;LATIN SMALL LETTER Q
    (|question| #\U+003F) ;QUESTION MARK
    (|questiondown| #\U+00BF) ;INVERTED QUESTION MARK
    (|quotedbl| #\U+0022) ;QUOTATION MARK
    (|quotedblbase| #\U+201E) ;DOUBLE LOW-9 QUOTATION MARK
    (|quotedblleft| #\U+201C) ;LEFT DOUBLE QUOTATION MARK
    (|quotedblright| #\U+201D) ;RIGHT DOUBLE QUOTATION MARK
    (|quoteleft| #\U+2018) ;LEFT SINGLE QUOTATION MARK
    (|quotereversed| #\U+201B) ;SINGLE HIGH-REVERSED-9 QUOTATION MARK
    (|quoteright| #\U+2019) ;RIGHT SINGLE QUOTATION MARK
    (|quotesinglbase| #\U+201A) ;SINGLE LOW-9 QUOTATION MARK
    (|quotesingle| #\U+0027) ;APOSTROPHE
    (|r| #\U+0072) ;LATIN SMALL LETTER R
    (|racute| #\U+0155) ;LATIN SMALL LETTER R WITH ACUTE
    (|radical| #\U+221A) ;SQUARE ROOT
    (|rcaron| #\U+0159) ;LATIN SMALL LETTER R WITH CARON
    (|reflexsubset| #\U+2286) ;SUBSET OF OR EQUAL TO
    (|reflexsuperset| #\U+2287) ;SUPERSET OF OR EQUAL TO
    (|registered| #\U+00AE) ;REGISTERED SIGN
    (|revlogicalnot| #\U+2310) ;REVERSED NOT SIGN
    (|rho| #\U+03C1) ;GREEK SMALL LETTER RHO
    (|ring| #\U+02DA) ;RING ABOVE
    (|rtblock| #\U+2590) ;RIGHT HALF BLOCK
    (|s| #\U+0073) ;LATIN SMALL LETTER S
    (|sacute| #\U+015B) ;LATIN SMALL LETTER S WITH ACUTE
    (|scaron| #\U+0161) ;LATIN SMALL LETTER S WITH CARON
    (|scedilla| #\U+015F) ;LATIN SMALL LETTER S WITH CEDILLA
    (|scircumflex| #\U+015D) ;LATIN SMALL LETTER S WITH CIRCUMFLEX
    (|second| #\U+2033) ;DOUBLE PRIME
    (|section| #\U+00A7) ;SECTION SIGN
    (|semicolon| #\U+003B) ;SEMICOLON
    (|seven| #\U+0037) ;DIGIT SEVEN
    (|seveneighths| #\U+215E) ;VULGAR FRACTION SEVEN EIGHTHS
    (|shade| #\U+2592) ;MEDIUM SHADE
    (|sigma| #\U+03C3) ;GREEK SMALL LETTER SIGMA
    (|sigma1| #\U+03C2) ;GREEK SMALL LETTER FINAL SIGMA
    (|similar| #\U+223C) ;TILDE OPERATOR
    (|six| #\U+0036) ;DIGIT SIX
    (|slash| #\U+002F) ;SOLIDUS
    (|smileface| #\U+263A) ;WHITE SMILING FACE
    (|space| #\U+0020) ;SPACE
    (|spade| #\U+2660) ;BLACK SPADE SUIT
    (|sterling| #\U+00A3) ;POUND SIGN
    (|suchthat| #\U+220B) ;CONTAINS AS MEMBER
    (|summation| #\U+2211) ;N-ARY SUMMATION
    (|sun| #\U+263C) ;WHITE SUN WITH RAYS
    (|t| #\U+0074) ;LATIN SMALL LETTER T
    (|tau| #\U+03C4) ;GREEK SMALL LETTER TAU
    (|tbar| #\U+0167) ;LATIN SMALL LETTER T WITH STROKE
    (|tcaron| #\U+0165) ;LATIN SMALL LETTER T WITH CARON
    (|therefore| #\U+2234) ;THEREFORE
    (|theta| #\U+03B8) ;GREEK SMALL LETTER THETA
    (|theta1| #\U+03D1) ;GREEK THETA SYMBOL
    (|thorn| #\U+00FE) ;LATIN SMALL LETTER THORN
    (|three| #\U+0033) ;DIGIT THREE
    (|threeeighths| #\U+215C) ;VULGAR FRACTION THREE EIGHTHS
    (|threequarters| #\U+00BE) ;VULGAR FRACTION THREE QUARTERS
    (|tilde| #\U+02DC) ;SMALL TILDE
    (|tildecomb| #\U+0303) ;COMBINING TILDE
    (|tonos| #\U+0384) ;GREEK TONOS
    (|trademark| #\U+2122) ;TRADE MARK SIGN
    (|triagdn| #\U+25BC) ;BLACK DOWN-POINTING TRIANGLE
    (|triaglf| #\U+25C4) ;BLACK LEFT-POINTING POINTER
    (|triagrt| #\U+25BA) ;BLACK RIGHT-POINTING POINTER
    (|triagup| #\U+25B2) ;BLACK UP-POINTING TRIANGLE
    (|two| #\U+0032) ;DIGIT TWO
    (|twodotenleader| #\U+2025) ;TWO DOT LEADER
    (|twothirds| #\U+2154) ;VULGAR FRACTION TWO THIRDS
    (|u| #\U+0075) ;LATIN SMALL LETTER U
    (|uacute| #\U+00FA) ;LATIN SMALL LETTER U WITH ACUTE
    (|ubreve| #\U+016D) ;LATIN SMALL LETTER U WITH BREVE
    (|ucircumflex| #\U+00FB) ;LATIN SMALL LETTER U WITH CIRCUMFLEX
    (|udieresis| #\U+00FC) ;LATIN SMALL LETTER U WITH DIAERESIS
    (|ugrave| #\U+00F9) ;LATIN SMALL LETTER U WITH GRAVE
    (|uhorn| #\U+01B0) ;LATIN SMALL LETTER U WITH HORN
    (|uhungarumlaut| #\U+0171) ;LATIN SMALL LETTER U WITH DOUBLE ACUTE
    (|umacron| #\U+016B) ;LATIN SMALL LETTER U WITH MACRON
    (|underscore| #\U+005F) ;LOW LINE
    (|underscoredbl| #\U+2017) ;DOUBLE LOW LINE
    (|union| #\U+222A) ;UNION
    (|universal| #\U+2200) ;FOR ALL
    (|uogonek| #\U+0173) ;LATIN SMALL LETTER U WITH OGONEK
    (|upblock| #\U+2580) ;UPPER HALF BLOCK
    (|upsilon| #\U+03C5) ;GREEK SMALL LETTER UPSILON
    (|upsilondieresis| #\U+03CB) ;GREEK SMALL LETTER UPSILON WITH DIALYTIKA
    (|upsilondieresistonos| #\U+03B0) ;GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND TONOS
    (|upsilontonos| #\U+03CD) ;GREEK SMALL LETTER UPSILON WITH TONOS
    (|uring| #\U+016F) ;LATIN SMALL LETTER U WITH RING ABOVE
    (|utilde| #\U+0169) ;LATIN SMALL LETTER U WITH TILDE
    (|v| #\U+0076) ;LATIN SMALL LETTER V
    (|w| #\U+0077) ;LATIN SMALL LETTER W
    (|wacute| #\U+1E83) ;LATIN SMALL LETTER W WITH ACUTE
    (|wcircumflex| #\U+0175) ;LATIN SMALL LETTER W WITH CIRCUMFLEX
    (|wdieresis| #\U+1E85) ;LATIN SMALL LETTER W WITH DIAERESIS
    (|weierstrass| #\U+2118) ;SCRIPT CAPITAL P
    (|wgrave| #\U+1E81) ;LATIN SMALL LETTER W WITH GRAVE
    (|x| #\U+0078) ;LATIN SMALL LETTER X
    (|xi| #\U+03BE) ;GREEK SMALL LETTER XI
    (|y| #\U+0079) ;LATIN SMALL LETTER Y
    (|yacute| #\U+00FD) ;LATIN SMALL LETTER Y WITH ACUTE
    (|ycircumflex| #\U+0177) ;LATIN SMALL LETTER Y WITH CIRCUMFLEX
    (|ydieresis| #\U+00FF) ;LATIN SMALL LETTER Y WITH DIAERESIS
    (|yen| #\U+00A5) ;YEN SIGN
    (|ygrave| #\U+1EF3) ;LATIN SMALL LETTER Y WITH GRAVE
    (|z| #\U+007A) ;LATIN SMALL LETTER Z
    (|zacute| #\U+017A) ;LATIN SMALL LETTER Z WITH ACUTE
    (|zcaron| #\U+017E) ;LATIN SMALL LETTER Z WITH CARON
    (|zdotaccent| #\U+017C) ;LATIN SMALL LETTER Z WITH DOT ABOVE
    (|zero| #\U+0030) ;DIGIT ZERO
    (|zeta| #\U+03B6) ;GREEK SMALL LETTER ZETA
    ))
